app/urls.py
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register("books", views.BookViewSet)
router.register("authors", views.AuthorViewSet)

app_name = "books"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", RedirectView.as_view(url="/books/")),
    path("books/", views.book_list, name="books"),
    path("books/<int:book_id>/", views.book_info, name="book_info"),
    path("authors/", views.author_list, name="authors"),
    path("authors/<int:author_id>/", views.author_info, name="author_info"),
]

bamazon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [path("admin/", admin.site.urls), path("", include("app.urls"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.core.exceptions import ValidationError
import os, uuid
from django_resized import ResizedImageField


def get_file_path(instance, filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join("images", filename)


class Author(models.Model):
    full_name = models.CharField(max_length=60)
    description = models.TextField(max_length=500)
    birth_date = models.DateField()
    death_date = models.DateField(null=True, blank=True)
    photo = ResizedImageField(
        size=[500, 500], quality=100, upload_to=get_file_path, blank=True
    )

    def __str__(self):
        return self.full_name

    def clean(self, *args, **kwargs):
        # run the base validation
        super(Author, self).clean(*args, **kwargs)

        # Don't allow dates earlier than birth date.
        if not self.death_date:
            return
        if self.birth_date > self.death_date:
            raise ValidationError("Death time must be later birth date.")


class Book(models.Model):
    author = models.ManyToManyField(Author, related_name="author")
    title = models.CharField(max_length=32)
    description = models.TextField(max_length=360)
    release_date = models.DateField()
    photo = ResizedImageField(
        size=[500, 500], quality=100, upload_to=get_file_path, blank=True
    )

    def __str__(self):
        return self.title

app/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework import viewsets

from .models import Book, Author
from .serializers import BookSerializer, AuthorSerializer


def book_list(request):
    books = Book.objects.all()
    page = request.GET.get("page", 1)

    paginator = Paginator(books, 2)
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        books = paginator.page(paginator.num_pages)
    context = {"books": books}
    return render(request, "books/index.html", context)


def book_info(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    authors = book.author.all()
    return render(request, "books/detail.html", {"book": book, "authors": authors})


def author_list(request):
    authors = Author.objects.all()
    page = request.GET.get("page", 1)

    paginator = Paginator(authors, 10)
    try:
        authors = paginator.page(page)
    except PageNotAnInteger:
        authors = paginator.page(1)
    except EmptyPage:
        authors = paginator.page(paginator.num_pages)
    context = {"authors": authors}
    return render(request, "authors/index.html", context)


def author_info(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    books = get_list_or_404(Book, author=author_id)
    return render(request, "authors/detail.html", {"author": author, "books": books})


class BookViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class AuthorViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer

app/templates/authors/detail.html
{% extends "base.html" %}

{% block content %}
<table class="table">
    <tbody>
    <tr>
        <td>
            <h1>{{ author.full_name }}</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <h3>Birth date: {{ author.birth_date }}</h3>
            {% if author.death_date %}
                <h3>Death date: {{ author.death_date }}</h3>
            {% endif %}
            <h3>Description: {{ author.description }}</h3>

            {% if books  %}
                <h3>Books:
                {% for book in books %}
                    <a href="{% url 'books:book_info' book.id %}">{{ book.title }}</a>;
                {% endfor %}
                </h3>
            {% endif %}
        </td>
        <td>
            {% if author.photo %}
            <img src="{{ author.photo.url }}">
            {% endif %}
        </td>
    </tr>
    </tbody>
</table>
{% endblock %}

app/templates/authors/index.html
{% extends "base.html" %}

{% block content %}
{% if authors %}
    <ul>
    <h3>
    {% for author in authors %}
        <li><a href="{% url 'books:author_info' author.id %}">{{ author.full_name }}</a></li>
    {% endfor %}
    </h3>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Bamazon</title>
</head>
<body>
<div class="content container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <a class="navbar-brand" href="/">Bamazon</a>
        <button class="navbar-toggler" type="button" data-toggle='collapse' data-target='#navbarNavAltMarkup' aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class='navbar-toggler-icon'></span>
        </button>
        <div id='navbarNavAltMarkup' class='collapse navbar-collapse'>
            <div class='navbar-nav'>
                <a class='nav-item nav-link' href="{% url 'books:books' %}">Books</a>
                <a class='nav-item nav-link' href="{% url 'books:authors' %}">Authors</a>
            </div>
        </div>
    </nav>
    <div class='container mt-3 text-break'>
            {% block content %}
            {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

app/templates/books/detail.html
{% extends "base.html" %}

{% block content %}
<table class="table">
    <tbody>
    <tr>
        <td>
            <h1>Title: {{ book.title }}</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <h3>Description: {{ book.description }}</h3>
            <h3>Author{% if authors.count > 1 %}s{% endif %}:
                {% for author in authors %}
                    <a href="{% url 'books:author_info' author.id %}">{{ author.full_name }}</a>;
                {% endfor %}
            </h3>
            <h3>Release date: {{ book.release_date }}</h3>
        </td>
        <td>
            {% if book.photo %}
            <img src="{{ book.photo.url }}">
            {% endif %}
        </td>
    </tr>
    </tbody>
</table>
{% endblock %}

app/templates/books/index.html
{% extends "base.html" %}

{% block content %}

{% if books.has_other_pages %}
{% if books %}
<h3>
    <ul>
    {% for book in books %}
        <li><a href="{% url 'books:book_info' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
    </ul>
</h3>
 <ul class="pagination">
    {% if books.has_previous %}
      <li><a class="page-item page-link" href="?page={{ books.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in books.paginator.page_range %}
      {% if books.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if books.has_next %}
      <li><a class="page-item page-link" href="?page={{ books.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
{% endif %}
{% endblock %}